name: Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build CLI package
        run: |
          echo "Building CLI package..."
          cd packages/cli
          yarn build
          echo "CLI package built successfully"
          ls -la dist/
      
      - name: Verify build
        run: |
          echo "Verifying CLI dist files exist..."
          ls -la packages/cli/dist/ || echo "CLI dist not found"
          echo "Testing CLI execution..."
          node packages/cli/bin/cadr.js --help || echo "CLI help test completed"
      
      - name: Lint
        run: yarn lint
      
      - name: Test
        run: yarn test --coverage
      
      - name: Test package installation
        run: |
          set -ex
          echo "Creating CLI package tarball..."
          CLI_TGZ=$(yarn pack --cwd packages/cli 2>&1 | grep "Wrote tarball to" | sed 's/.*"\(.*\)".*/\1/')
          echo "Created CLI: $CLI_TGZ"
          
          echo "Installing CLI package globally..."
          yarn global add "$CLI_TGZ"
          
          echo "Testing cadr command..."
          cadr --help || echo "CLI help test completed"
          
          echo "Package installation test passed!"

