name: Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build core package first
        run: |
          echo "Building core package first..."
          cd packages/core
          yarn build
          echo "Core package built successfully"
          ls -la dist/
      
      - name: Build all packages
        run: yarn build
      
      - name: Verify build
        run: |
          echo "Checking if @cadr/core is built..."
          ls -la packages/core/dist/
          echo "Testing module resolution from CLI package..."
          cd packages/cli
          node -e "console.log('Core module resolved to:', require.resolve('@cadr/core'))"
          echo "Checking CLI can import core..."
          node -e "const core = require('@cadr/core'); console.log('Core imported successfully:', Object.keys(core))"
      
      - name: Lint
        run: yarn lint
      
      - name: Test
        run: yarn test --coverage
      
      - name: Test package installation
        run: |
          set -ex
          echo "Creating core package tarball..."
          CORE_TGZ=$(yarn pack --cwd packages/core)
          echo "Created core: $CORE_TGZ"
          
          echo "Creating CLI package tarball..."
          CLI_TGZ=$(yarn pack --cwd packages/cli)
          echo "Created CLI: $CLI_TGZ"
          
          echo "Installing packages globally..."
          yarn global add "$CORE_TGZ"
          yarn global add "$CLI_TGZ"
          
          echo "Verifying installation..."
          yarn global list | grep cadr-cli || echo "Package not found in global list"
          
          echo "Checking yarn bin directory..."
          echo "yarn global bin: $(yarn global bin)"
          ls -la "$(yarn global bin)" | grep cadr || echo "cadr not found in bin directory"
          
          echo "Testing cadr command..."
          which cadr || echo "cadr not in PATH"
          cadr
          
          echo "Package installation test passed!"
        shell: bash
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
        continue-on-error: true
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false

