name: Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Allow creating commits
      pull-requests: write # Allow creating pull requests

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build CLI package
        run: |
          echo "Building CLI package..."
          cd packages/cli
          yarn build
          echo "CLI package built successfully"
          ls -la dist/
      
      - name: Verify build
        run: |
          echo "Verifying CLI dist files exist..."
          ls -la packages/cli/dist/ || echo "CLI dist not found"
          echo "Testing CLI execution..."
          node packages/cli/dist/index.js --help || echo "CLI help test completed"
      
      - name: Lint
        run: yarn lint
      
      - name: Test
        run: yarn test --coverage
      
      - name: Update coverage in README
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: node .github/scripts/update-coverage.js
      
      - name: Create Pull Request for coverage update
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update coverage badge and report [skip ci]'
          title: 'chore: Update test coverage report'
          body: |
            ## Automated Coverage Update
            
            This PR updates the coverage badge and table in the README with the latest test coverage data.
            
            **Generated by**: GitHub Actions workflow
            **Triggered by**: Merge to main branch
            
            ### Changes
            - Coverage badge updated with current percentage
            - Coverage table updated with detailed metrics
            
            ---
            *This is an automated PR. Please review and merge to keep coverage reporting up-to-date.*
          branch: coverage-update
          branch-suffix: timestamp
          delete-branch: true
          labels: |
            automated
            documentation
            skip-changelog
      
      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage/
            !coverage/**/*.json
          retention-days: 30
      
      - name: Test package installation
        run: |
          set -ex
          echo "Creating CLI package tarball..."
          CLI_TGZ=$(yarn pack --cwd packages/cli 2>&1 | grep "Wrote tarball to" | sed 's/.*"\(.*\)".*/\1/')
          echo "Created CLI: $CLI_TGZ"
          
          echo "Installing CLI package globally..."
          yarn global add "$CLI_TGZ"
          
          echo "Testing cadr command..."
          cadr --help || echo "CLI help test completed"
          
          echo "Package installation test passed!"

